name: Run Experiment

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

#inputs:
#  experiments:
#    required: false
#    description: early-stopping.ipynb, early-stopping_output.ipynb, kubeflow-e2e-mnist.ipynb, mpi-job-horovod.py
#    default: ""
#  training-operator:
#    required: false
#    description: whether to deploy training-operator or not
#    default: false
#  trial-images:
#    required: false
#    description: comma delimited trial image name
#    default: ""
#  katib-ui:
#    required: true
#    description: whether to deploy katib-ui or not
#    default: false
#  database-type:
#    required: false
#    description: mysql or postgres
#    default: mysql
#  tune-api:
#    required: true
#    description: whether to execute tune-api test or not
#    default: false

jobs:
  run-experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Environment
        shell: bash
        run: |
          # Define the experiments as a comma-separated string
          EXPERIMENTS="early-stopping.ipynb,early-stopping_output.ipynb,kubeflow-e2e-mnist.ipynb,mpi-job-horovod.py"
          echo "EXPERIMENTS=$EXPERIMENTS" >> $GITHUB_ENV
      - name: Setup Minikube Cluster
        shell: bash
        run: ./test/e2e/v1beta1/scripts/gh-actions/setup-minikube.sh

      - name: Setup Katib
        shell: bash
        run: ./test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh

      - name: Run E2E Experiment
        shell: bash
        run: |
          if "${{ inputs.tune-api }}"; then
            ./test/e2e/v1beta1/scripts/gh-actions/run-e2e-tune-api.sh
          else
            ./test/e2e/v1beta1/scripts/gh-actions/run-e2e-experiment-papermill.sh "$EXPERIMENTS"
          fi
