name: Run e2e tests with papermill

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  run-experiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install papermill

      - name: Set Up Environment
        shell: bash
        run: |
          # Define the experiments as a comma-separated string
          EXPERIMENTS="early-stopping.ipynb,early-stopping_output.ipynb,kubeflow-e2e-mnist.ipynb,mpi-job-horovod.py"
          
          # Convert comma-separated string to an array
          IFS=',' read -r -a EXPERIMENTS_ARRAY <<< "$EXPERIMENTS"
          echo "EXPERIMENTS_ARRAY=${EXPERIMENTS_ARRAY[@]}" >> $GITHUB_ENV

      - name: Print working directory
        run: |
          pwd

      - name: Run experiment
        shell: bash
        run: |
          ./test/e2e/v1beta1/scripts/gh-actions/run-e2e-experiment-papermill.sh "$EXPERIMENTS"

