name: Run e2e tests with papermill

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  run-experiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2

      - name: Set up Kind Cluster
        uses: helm/kind-action@v1
        with:
          version: v0.17.0
          config: ./test/e2e/v1beta1/scripts/gh-actions/kind-config.yaml

      - name: Grant execute permission to the script
        run: chmod +x ./test/e2e/v1beta1/scripts/gh-actions/setup-kubeflow.sh

      - name: deploy kubeflow
        shell: bash
        run: |
          ./test/e2e/v1beta1/scripts/gh-actions/setup-kubeflow.sh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install papermill jupyter ipykernel requests==2.28.1 urllib3==1.26.15 requests_toolbelt==0.9.1
          python -m ipykernel install --user --name python3 --display-name "Python 3"

      - name: Set Up Environment
        shell: bash
        run: |
          # Define the experiments as a comma-separated string
          EXPERIMENTS="early-stopping.ipynb,early-stopping_output.ipynb,kubeflow-e2e-mnist.ipynb,mpi-job-horovod.py"
          echo "EXPERIMENTS=$EXPERIMENTS" >> $GITHUB_ENV
          echo "experiments are = $EXPERIMENTS"

      - name: Print working directory
        run: |
          pwd

      - name: Print directory tree
        run: |
          sudo apt-get update
          sudo apt-get install tree
          tree

      - name: Grant execute permission to the script
        run: chmod +x ./test/e2e/v1beta1/scripts/gh-actions/run-e2e-tests-papermill.sh

      - name: Run experiment
        shell: bash
        run: |
          ./test/e2e/v1beta1/scripts/gh-actions/run-e2e-tests-papermill.sh "$EXPERIMENTS"

