name: Run e2e sdk tests with papermill

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  run-experiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Setup Minikube Cluster
        shell: bash
        run: ./test/e2e/v1beta1/scripts/gh-actions/setup-minikube.sh true false "" "" false

      - name: Setup Katib
        shell: bash
        run: ./test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh true

#      - name: setup cluster
#        run: |
#          chmod +x ./test/e2e/v1beta1/scripts/gh-actions/create-cluster.sh
#          ./test/e2e/v1beta1/scripts/gh-actions/create-cluster.sh
#
#      - name: setup katib
#        run: |
#          chmod +x ./test/e2e/v1beta1/scripts/gh-actions/new-setup-katib.sh
#          ./test/e2e/v1beta1/scripts/gh-actions/new-setup-katib.sh

#      - name: setup cluster & katib
#        run: |
#          ./examples/v1beta1/kind-cluster/deploy.sh
#
#      - name: setup pipelines
#        run: |
#          chmod +x ./test/e2e/v1beta1/scripts/gh-actions/setup-pipelines.sh
#          ./test/e2e/v1beta1/scripts/gh-actions/setup-pipelines.sh
        

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install papermill kubeflow-katib jupyter ipykernel
          python -m ipykernel install --user --name python3 --display-name "Python 3"
#           requests==2.28.1 urllib3==1.26.15 requests_toolbelt==0.9.1

      - name: Set Up Environment
        shell: bash
        run: |
          # Define the experiments as a comma-separated string
          EXPERIMENTS="nas-with-darts.ipynb"
          echo "EXPERIMENTS=$EXPERIMENTS" >> $GITHUB_ENV
          echo "experiments are = $EXPERIMENTS"

      - name: Print working directory
        run: |
          pwd

      - name: Print directory tree
        run: |
          sudo apt-get update
          sudo apt-get install tree
          tree

      - name: Run experiment
        run: |
          chmod +x ./test/e2e/v1beta1/scripts/gh-actions/run-e2e-sdk-tests-papermill.sh
          ./test/e2e/v1beta1/scripts/gh-actions/run-e2e-sdk-tests-papermill.sh "$EXPERIMENTS"
